### ISSUE TITLE
Add page about Community Sprints

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight.github.io#130]

**Comment by reinacmurray** [comment]
Hi @karenmajewicz, for some reason I can't assign this to myself, but i've begun working on it.

**Comment by karenmajewicz** [comment]
Great! I will try to add you to the user permissions.

**Comment by reinacmurray** [comment]
pull request made: https://github.com/geoblacklight/geoblacklight.github.io/pull/153
