### ISSUE TITLE
Migrate GeoBlacklight Documentation in the repository wiki into the website/Pages

### ISSUE THREAD

**Issue by sdellis** [geoblacklight/geoblacklight.github.io#161]
Since [Github Wiki content is not indexed](https://github.com/github/feedback/discussions/4992), it was decided during the February 2022 GeoBlacklight Sprint that we should migrate (and update, where necessary) the wiki content to the website. Metadata content is being actively updated, so this ticket ONLY applies to _non-metadata-oriented_ content.

**Comment by karenmajewicz** [comment]
Completed during sprint see #164
