### ISSUE TITLE
Consider how to relate the GeoBlacklight, OpenGeoMetadata, and OpenIndexMaps projects

### ISSUE THREAD

**Issue by karenmajewicz** [geoblacklight/geoblacklight.github.io#186]
These projects are separate sites, but closely interrelated. How might we better link them into the same ecosystem?

Some brainstorm ideas we discussed at the last standup:
- [ ] add OpenIndexMaps (OIM) as a subset of the OpenGeoMetadata (OGM) project
- [ ] add OIM and OGM to the projects page of the GBL website
- [ ] create an overarching community name that connects these 3 projects, leaving space for others as well
- [ ] does Geo4LibCamp fit in as well?

**Comment by ewlarson** [comment]
Closing. Transferring to Geo4LibCamp committee.
