### ISSUE TITLE
Add documentation about user authentication backends

### ISSUE THREAD

**Issue by mradamcox** [geoblacklight/geoblacklight.github.io#241]
A summary of what login/account/bookmark capabilities come with GeoBlacklight out-of-the-box would be very helpful, plus some information about how integrations with existing institutional authentication systems can be set up (which I believe is common in institutional deployments).

These capabilities may be inherited from Blacklight, in which case maybe pointing upstream to that documentation (if it exists) would be sufficient.

**Comment by karenmajewicz** [comment]
https://geoblacklight.org/docs/user_authentication/
