### ISSUE TITLE
update Digital Initiatives link in Lewis and Clark box

### ISSUE THREAD

**Issue by jeremymcwilliams** [geoblacklight/geoblacklight.github.io#79]
Could the Watzek Digital Initiatives link be updated to "http://library.lclark.edu/digital-initiatives" in the showcase section for lewis and clark? thank you!

![geoblacklight](https://user-images.githubusercontent.com/1103262/30399942-3192fbca-988a-11e7-979c-91a5d301025e.png)

**Comment by eliotjordan** [comment]
Should be `https://library.lclark.edu/digital-initiatives`
