### ISSUE TITLE
Use collections instead of posts for non-date things

### ISSUE THREAD

**Issue by ewlarson** [geoblacklight/geoblacklight.github.io#99]
We should use jekyll collections to avoid having old dates within URLs for things like our tutorial pages:
https://stackoverflow.com/questions/27099427/jekyll-filename-without-date

**Comment by mejackreed** [comment]
👍  can we do it in a way that the old posts get redirected?

**Comment by ewlarson** [comment]
I think we can get that done with https://github.com/jekyll/jekyll-redirect-from

**Comment by karenmajewicz** [comment]
Implemented new platform with static pages and blog posts
